version: '3.7'

services:

    docdb-database:
        image: mariadb:10.4.8
        volumes:
            - ${STORAGE_PATH}/var/lib/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
        secrets:
            - mariadb_root_password
        networks:
            - dcc-net
        restart: always

    rest-api:
        image: cosmicexplorer/rest-dcc:1.2.1
        init: true
        secrets:
            - mysql_docdbrw_passwd
        networks:
            - dcc-net
        restart: always

    oauth-database:
        image: postgres:9.6
        volumes:
            - ${STORAGE_PATH}/var/lib/postgresql/data:/var/lib/postgresql/data
        networks:
            - dcc-net
        restart: always

    oauth-server:
        image: oryd/hydra:v1.0.8
        environment:
            - SECRETS_SYSTEM=${SECRETS_SYSTEM}
            - DSN=postgres://hydra:${HYDRA_PASSWD}@oauth-database:5432/hydra?sslmode=disable
            - URLS_SELF_ISSUER=https://${DCC_INSTANCE}/oauth/
            - URLS_CONSENT=https://${DCC_INSTANCE}/consent
            - URLS_LOGIN=https://${DCC_INSTANCE}/login
            - LOG_LEVEL=debug
            - HTTPS_ALLOW_TERMINATION_FROM=172.30.101.0/24
        networks:
            - dcc-net
        command: "serve all"
        restart: always

    oauth-consent:
        image: cosmicexplorer/hydra-login-consent-node:1.0.9
        environment:
            - HYDRA_ADMIN_URL=http://oauth-server:4445
            - MOCK_TLS_TERMINATION=y
        secrets:
            - shib_header_secret
        networks:
            - dcc-net
        restart: always

networks:
    dcc-net:
        attachable: true
        ipam:
            config:
                - subnet: 172.30.101.0/24

secrets:
    mariadb_root_password:
        file: ./mariadb_root_password.txt
    mysql_docdbrw_passwd:
        file: ./mysql_docdbrw_passwd.txt
    shib_header_secret:
        file: ./shib_header_secret.txt
