version: '3.7'

services:

    docdb-database:
        image: mariadb:10.2
        volumes:
            - /srv/docker/dcc/var/lib/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
        secrets:
            - mariadb_root_password
        networks:
            - default
        deploy:
            replicas: 1

    rest-api:
        image: cosmicexplorer/rest-dcc:latest
        init: true
        secrets:
            - mysql_docdbrw_passwd
        networks:
            - default
        ports:
            - "8443:8443"
        deploy:
            replicas: 1

secrets:
    mariadb_root_password:
        external: true
    mysql_docdbrw_passwd:
        external: true

