version: '3.7'

services:

    letsencrypt:
        image: linuxserver/letsencrypt
        environment:
            - PUID=${UID}
            - PGID=${GROUPS}
            - TZ=America/New_York
            - URL=${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}
            - VALIDATION=http
            - EMAIL=
            - DHLEVEL=2048
            - ONLY_SUBDOMAINS=false
            - STAGING=false
        volumes:
            - ${STORAGE_PATH}/letsencrypt/config:/config
        networks:
            - roster-net
        ports:
            - "80:80"
        deploy:
          replicas: 0

    comanage-registry-database:
        image: mariadb:10.2
        volumes:
            - ${STORAGE_PATH}/var/lib/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
            - MYSQL_DATABASE=registry
            - MYSQL_USER=registry_user
            - MYSQL_PASSWORD_FILE=/run/secrets/mariadb_password
        secrets:
            - mariadb_root_password
            - mariadb_password
        networks:
            - roster-net
        deploy:
            replicas: 1

    comanage-registry:
        image: comanage-registry:${COMANAGE_REGISTRY_VERSION}-shibboleth-sp-${COMANAGE_REGISTRY_SHIBBOLETH_SP_IMAGE_VERSION}
        volumes:
            - ${STORAGE_PATH}/srv/comanage-registry/local:/srv/comanage-registry/local
            - ${STORAGE_PATH}/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
            - ${STORAGE_PATH}/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml
            - ${STORAGE_PATH}/etc/shibboleth/inc-md-cert.pem:/etc/shibboleth/inc-md-cert.pem
            - ${STORAGE_PATH}/letsencrypt/config/etc/letsencrypt:/etc/letsencrypt
        environment:
            - COMANAGE_REGISTRY_ENABLE_PLUGIN=${COMANAGE_REGISTRY_ENABLE_PLUGIN}
            - COMANAGE_REGISTRY_ADMIN_GIVEN_NAME=${COMANAGE_REGISTRY_ADMIN_GIVEN_NAME}
            - COMANAGE_REGISTRY_ADMIN_FAMILY_NAME=${COMANAGE_REGISTRY_ADMIN_FAMILY_NAME}
            - COMANAGE_REGISTRY_ADMIN_USERNAME=${COMANAGE_REGISTRY_ADMIN_USERNAME}
            - COMANAGE_REGISTRY_DATASOURCE=Database/Mysql
            - COMANAGE_REGISTRY_DATABASE_USER_PASSWORD_FILE=/run/secrets/comanage_registry_database_user_password
            - COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN=${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}
            - COMANAGE_REGISTRY_EMAIL_FROM=array('comanage-do-not-reply@cosmicexplorer.org' => 'Cosmic Explorer COManage Registry')
            - COMANAGE_REGISTRY_EMAIL_TRANSPORT=Smtp
            - COMANAGE_REGISTRY_EMAIL_HOST=smtp-relay.syr.edu
            - COMANAGE_REGISTRY_EMAIL_PORT=25
            - HTTPS_CERT_FILE=/etc/letsencrypt/live/${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}/cert.pem
            - HTTPS_PRIVKEY_FILE=/etc/letsencrypt/live/${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}/privkey.pem
            - HTTPS_CHAIN_FILE=/etc/letsencrypt/live/${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}/fullchain.pem
            - SHIBBOLETH_SP_ENCRYPT_CERT=/run/secrets/shibboleth_sp_encrypt_cert
            - SHIBBOLETH_SP_ENCRYPT_PRIVKEY=/run/secrets/shibboleth_sp_encrypt_privkey
        secrets:
            - comanage_registry_database_user_password
            - shibboleth_sp_encrypt_cert
            - shibboleth_sp_encrypt_privkey
        networks:
            - roster-net
        ports:
            - "443:443"
        deploy:
            replicas: 0

    comanage-registry-ldap:
        image: comanage-registry-slapd:${COMANAGE_REGISTRY_SLAPD_IMAGE_VERSION}
        command: ["slapd", "-d", "256", "-h", "ldapi:/// ldap:/// ldaps:///", "-u", "openldap", "-g", "openldap"]
        volumes:
            - ${STORAGE_PATH}/var/lib/ldap:/var/lib/ldap
            - ${STORAGE_PATH}/etc/slapd.d:/etc/ldap/slapd.d
            - ${STORAGE_PATH}/letsencrypt/config/etc/letsencrypt:/etc/letsencrypt
        environment:
            - OLC_ROOT_PW_FILE=/run/secrets/olc_root_pw
            - OLC_SUFFIX=${OLC_SUFFIX}
            - OLC_ROOT_DN=${OLD_ROOT_DN}
            - SLAPD_CERT_FILE=/etc/letsencrypt/live/${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}/cert.pem
            - SLAPD_CHAIN_FILE=/etc/letsencrypt/live/${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}/fullchain.pem
            - SLAPD_PRIVKEY_FILE=/etc/letsencrypt/live/${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}/privkey.pem
        secrets:
            - olc_root_pw
        networks:
            - roster-net
        ports:
            - "389:389"
            - "636:636"
        deploy:
            replicas: 0

networks:
    roster-net:
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 172.30.100.0/24

secrets:
    comanage_registry_database_user_password:
        external: true
    mariadb_root_password:
        external: true
    mariadb_password:
        external: true
    shibboleth_sp_encrypt_cert:
        external: true
    shibboleth_sp_encrypt_privkey:
        external: true
    olc_root_pw:
        external: true
