version: '3.7'

services:

    letsencrypt:
        image: linuxserver/letsencrypt
        environment:
            - PUID=${UID}
            - PGID=${GROUPS}
            - TZ=America/New_York
            - URL=${COMANAGE_REGISTRY_VIRTUAL_HOST_FQDN}
            - VALIDATION=http
            - EMAIL=
            - DHLEVEL=2048
            - ONLY_SUBDOMAINS=false
            - STAGING=false
        volumes:
            - ${STORAGE_PATH}/letsencrypt/config:/config
        networks:
            roster-bridge:
                ipv4_address: 192.168.100.2
        ports:
            - "128.230.146.12:80:80"
        restart: always

networks:
    roster-bridge:
        attachable: true
        ipam:
            driver: bridge
            config:
                - subnet: 192.168.100.0/24
                - ip_range: 192.168.100.0/24
                - gateway: 192.168.100.1
        driver_opts:
            com.docker.network.bridge.name: "roster-bridge"
            com.docker.network.bridge.host_binding_ipv4: "128.230.146.12"
                
