version: '3.7'

services:
    postfix:
        image: cosmicexplorer/mailman-postfix:2
        volumes:
            - ${STORAGE_PATH}:/opt/mailman
        environment:
            - POSTFIX_MYHOSTNAME=${POSTFIX_MAILNAME}
            - POSTFIX_MYNETWORKS=${POSTFIX_MYNETWORKS}
        ports:
            - "128.230.146.15:25:25"
        networks:
            mailman-bridge:
                ipv4_address: 192.168.102.3
            mailman-net: {}
        restart: always

networks:
    mailman-net:
        external: true
        name: mail_mailman-net
    mailman-bridge:
        external: true
        name: mail_mailman-bridge
