version: '3.7'

services:
    mailman-web:
        image: cosmicexplorer/mailman-web:0.2.1
        volumes:
            - /srv/docker/mailman/web:/opt/mailman-web-data
        environment:
            - MAILMAN_DATABASE_URL_FILE=/run/secrets/mailman_database_url
            - MAILMAN_DATABASE_TYPE=postgres
            - HYPERKITTY_API_KEY_FILE=/run/secrets/hyperkitty_api_key
            - SERVE_FROM_DOMAIN=${SERVE_FROM_DOMAIN}
            - MAILMAN_ADMIN_USER=${MAILMAN_ADMIN_USER}
            - MAILMAN_ADMIN_EMAIL=${MAILMAN_ADMIN_EMAIL}
            - MAILMAN_WEB_SECRET_KEY_FILE=/run/secrets/mailman_web_secret_key
            - MAILMAN_REST_USER=restadmin
            - MAILMAN_REST_PASSWORD_FILE=/run/secrets/mailman_rest_password
            - SMTP_HOST=postfix
            - SMTP_PORT=25
        networks:
            roster-net: {}
        secrets:
            - hyperkitty_api_key
            - mailman_database_url
            - mailman_rest_password
            - mailman_web_secret_key
        restart: always

networks:
    roster-net:
        external: true
        name: roster_roster-net
        
secrets:
    hyperkitty_api_key:
        file: ./hyperkitty_api_key.txt
    mailman_database_url:
        file: ./mailman_database_url.txt
    mailman_rest_password:
        file: ./mailman_rest_password.txt
    mailman_web_secret_key:
        file: ./mailman_web_secret_key.txt
