version: '3.7'

services:

    database:
        image: postgres:9.6
        volumes:
            - ${STORAGE_PATH}/database:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=mailmandb
            - POSTGRES_USER=mailman
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        networks:
            roster-net: {}
        secrets:
            - postgres_password
        restart: always

networks:
    roster-net:
        external: true
        name: roster_roster-net

secrets:
    postgres_password:
        file: ./postgres_password.txt
