version: '3.3'

networks:
    default:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: ${POSTFIX_MYNETWORKS}

services:

    letsencrypt:
        image: linuxserver/letsencrypt
        environment:
            - PUID=${UID}
            - PGID=${GROUPS}
            - TZ=America/New_York
            - URL=${VIRTUAL_HOST_FQDN}
            - VALIDATION=http
            - EMAIL=
            - DHLEVEL=2048
            - ONLY_SUBDOMAINS=false
            - STAGING=false
        volumes:
            - ${STORAGE_PATH}/letsencrypt/config:/config
        networks:
            - default
        ports:
            - "80:80"
        deploy:
          replicas: 1

    mailman-core:
        image: cosmicexplorer/mailman-core:0.2.1
        volumes:
            - ${STORAGE_PATH}/core:/opt/mailman/
        environment:
            - MAILMAN_DATABASE_URL_FILE=/run/secrets/mailman_database_url
            - MAILMAN_DATABASE_TYPE=postgres
            - MAILMAN_DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
            - HYPERKITTY_API_KEY_FILE=/run/secrets/hyperkitty_api_key
            - MAILMAN_REST_USER=restadmin
            - MAILMAN_REST_PASSWORD_FILE=/run/secrets/mailman_rest_password
            - SMTP_HOST=postfix
            - SMTP_PORT=25
        stop_grace_period: 30s
        networks:
            - default
        secrets:
            - hyperkitty_api_key
            - mailman_database_url
            - mailman_rest_password
        deploy:
            replicas: 1
            endpoint_mode: dnsrr

    mailman-web:
        image: cosmicexplorer/mailman-web:0.2.1
        volumes:
            - ${STORAGE_PATH}/web:/opt/mailman-web-data
            - ${STORAGE_PATH}/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
            - ${STORAGE_PATH}/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml
            - ${STORAGE_PATH}/etc/shibboleth/inc-md-cert.pem:/etc/shibboleth/inc-md-cert.pem
        environment:
            - MAILMAN_DATABASE_URL_FILE=/run/secrets/mailman_database_url
            - MAILMAN_DATABASE_TYPE=postgres
            - HYPERKITTY_API_KEY_FILE=/run/secrets/hyperkitty_api_key
            - SERVE_FROM_DOMAIN=${SERVE_FROM_DOMAIN}
            - MAILMAN_ADMIN_USER=${MAILMAN_ADMIN_USER}
            - MAILMAN_ADMIN_EMAIL=${MAILMAN_ADMIN_EMAIL}
            - MAILMAN_WEB_SECRET_KEY_FILE=/run/secrets/mailman_web_secret_key
            - MAILMAN_REST_USER=restadmin
            - MAILMAN_REST_PASSWORD_FILE=/run/secrets/mailman_rest_password
            - SMTP_HOST=postfix
            - SMTP_PORT=25
        networks:
            - default
        secrets:
            - hyperkitty_api_key
            - mailman_database_url
            - mailman_rest_password
            - mailman_web_secret_key
        deploy:
            replicas: 1
            endpoint_mode: dnsrr

    database:
        image: postgres:9.6
        volumes:
            - ${STORAGE_PATH}/database:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=mailmandb
            - POSTGRES_USER=mailman
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        networks:
            - default
        secrets:
            - postgres_password
        deploy:
            replicas: 1
            endpoint_mode: dnsrr

    postfix:
        image: cosmicexplorer/mailman-postfix:latest
        volumes:
            - ${STORAGE_PATH}:/opt/mailman
        environment:
            - POSTFIX_MAILNAME=${POSTFIX_MAILNAME}
            - POSTFIX_MYHOSTNAME=${POSTFIX_MYHOSTNAME}
            - POSTFIX_MYNETWORKS=${POSTFIX_MYNETWORKS}
        ports:
            - target: 25
              published: 25
              # 'host' mode is necessary for Postfix to receive the connection IP address
              # instead of the ingress network IP address. This is only a useful workaround
              # when not truly leveraging the load balancing capabilities of swarm mode.
              # Normally with more than a single mode swarm the upstream load balancer in
              # front of the swarm would be used for the definitive access log.
              # See discussion at https://github.com/moby/moby/issues/25526 .
              mode: host
        networks:
            - default
        deploy:
            replicas: 1
            endpoint_mode: dnsrr

    apache:
        image: cosmicexplorer/mailman-core-apache-shib:latest
        volumes:
            - ${STORAGE_PATH}/web:/opt/mailman-web-data
            - ${STORAGE_PATH}/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
            - ${STORAGE_PATH}/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml
            - ${STORAGE_PATH}/letsencrypt/config/etc/letsencrypt:/etc/letsencrypt
        environment:
            - HTTPS_CERT_FILE=/etc/letsencrypt/live/${VIRTUAL_HOST_FQDN}/cert.pem
            - HTTPS_PRIVKEY_FILE=/etc/letsencrypt/live/${VIRTUAL_HOST_FQDN}/privkey.pem
            - HTTPS_CHAIN_FILE=/etc/letsencrypt/live/${VIRTUAL_HOST_FQDN}/fullchain.pem
            - HTTPS_KEY_FILE=/run/secrets/https_privkey_file
            - MAILMAN_ADMIN_EMAIL=dabrown@syr.edu
            - SHIBBOLETH_SP_ENCRYPT_CERT=/run/secrets/shibboleth_sp_encrypt_cert
            - SHIBBOLETH_SP_ENCRYPT_PRIVKEY=/run/secrets/shibboleth_sp_encrypt_privkey
            - VIRTUAL_HOST_FQDN=sugwg-scitokens.phy.syr.edu
        secrets:
            - shibboleth_sp_encrypt_cert
            - shibboleth_sp_encrypt_privkey
        networks:
            - default
        ports:
            - target: 443
              published: 443
              protocol: tcp
              # 'host' mode is necessary for nginx to receive the browser IP address
              # instead of the ingress network IP address. This is only a useful workaround
              # when not truly leveraging the load balancing capabilities of swarm mode.
              # Normally with more than a single mode swarm the upstream load balancer in
              # front of the swarm would be used for the definitive access log.
              # See discussion at https://github.com/moby/moby/issues/25526 .
              mode: host
        deploy:
            replicas: 0
            endpoint_mode: dnsrr

secrets:
    hyperkitty_api_key:
        external: true
    mailman_database_url:
        external: true
    mailman_rest_password:
        external: true
    mailman_web_secret_key:
        external: true
    postgres_password:
        external: true
    shibboleth_sp_encrypt_cert:
        external: true
    shibboleth_sp_encrypt_privkey:
        external: true
